### ISSUE TITLE
CompilerAttributes causes errors in .NET Standard 1.3 and .NET Standard 2.0

### ISSUE THREAD

**Issue by Discjoggy** [gregsdennis/Manatee.Json#201]
Hi,

I want to use your library in a Unity3d project. For that I had to create a project and check out the NuGet packages (would be nice to find the DLL files in the release section of this repo too). Then I used the .NET Standard 2.0 DLL file but it produces the following error:

```
Assembly 'Assets/Plugins/Manatee.Json.dll' will not be loaded due to errors:
Unable to resolve reference 'CompilerAttributes'. Is the assembly missing or incompatible with the current platform?
```

Even if I manually copy the `CompilerAttributes` DLL, it produces more errors of missing references. I tried to use the .NET 4.5 DLL and then it works as expected! So I removed the `CompilerAttributes` package reference and commented the single relevant line of the `Attributes.cs` file:

```cs
namespace Manatee.Json.Internal
{
#if !NET45
    //[CompilerAttributes.GeneratesWarning("This constructor is provided for deserialization purposes only.  Please use the parameterized one instead.")]
#endif
    internal class DeserializationUseOnlyAttribute : Attribute
    {
    }
}
```

With this change everything is working very well. Is there an incompatible dependency between .NET Standard 2.0 and the `CompilerAttributes` package? Temporary I use the working .NET 4.5 DLL but it would be nice to see the .NET Standard 2.0 DLL working too.

**Comment by gregsdennis** [comment]
Thanks for reporting this. I'll have a look.

I'm not experiencing this myself.  As you can probably see from the lines surrounding the line you commented, the compiler attributes library isn't used for 4.5, but it should be working for the other targets.

**Comment by gregsdennis** [comment]
Additionally, installing Nuget packages is the preferred method for inclusion of third-party libraries. What's your use case for wanting the DLLs directly?

**Comment by Discjoggy** [comment]
> Can you tell me what versions of the two libraries you're using, please?

For both I am using the current version 10.1.2.

> What's your use case for wanting the DLLs directly?

Unity doesn't support NuGet. Instead it is possible to use native or managed plugins as DLLs. That's why I am building the plugin in a separate .NET Standard 2.0 project and referencing to the NuGet dependency of Manatee in this project. The build process exports `Manatee.Json.dll` but `CompilerAttributes.dll` is missing. There is a way to export all used DLLs with `<CopyToOutputDirectory>Always</CopyToOutputDirectory>`, but is a way too much. I just expect from the release section that I can just download and directly use the DLLs in any compatible project but this is not the case.

**Comment by gregsdennis** [comment]
For the DLL issue, I suggest simply downloading the packages directly from Nuget and extracting the libraries yourself to get the direct reference that Unity is looking for.

You can change the *.nupkg* extension to *.zip* and extract it using your favorite ZIP tool.

**Comment by Discjoggy** [comment]
Yes I know, but the `CompilerAttributes.dll` is still missing in `.NET Standard 2.0`. Anyway I using the .NET 4.6 library..

**Comment by gregsdennis** [comment]
I'm removing this with the next version, which will also contain JSON Schema ~draft-08~ 2019-04. It's not working like I want anyway.

**Comment by gregsdennis** [comment]
@Discjoggy, I released 10.2.0-beta1 which contains your fix.
